# Fake News Detection - 01 Preprocessing

In [1]:
import os
import sys

sys.path.insert(0, '../src')

import polars as pl

from preprocessing import natural_language_cols, preprocess, preprocess_file

In [2]:
df_sample = pl.read_csv('../data/raw/news_sample.csv', n_rows=250)
df_sample.select(natural_language_cols).head()

shape: (5, 5)
┌─────────────────────┬─────────────────────┬─────────────────┬───────────────┬────────────────────┐
│ content             ┆ title               ┆ authors         ┆ meta_keywords ┆ meta_description   │
│ ---                 ┆ ---                 ┆ ---             ┆ ---           ┆ ---                │
│ str                 ┆ str                 ┆ str             ┆ str           ┆ str                │
╞═════════════════════╪═════════════════════╪═════════════════╪═══════════════╪════════════════════╡
│ Sometimes the power ┆ Church Congregation ┆ Ruth Harris     ┆ ['']          ┆ null               │
│ of Christm…         ┆ Brings Gif…         ┆                 ┆               ┆                    │
│ AWAKENING OF 12     ┆ AWAKENING OF 12     ┆ Zurich Times    ┆ ['']          ┆ null               │
│ STRANDS of DNA…     ┆ STRANDS of DNA…     ┆                 ┆               ┆                    │
│ Never Hike Alone: A ┆ Never Hike Alone -  ┆ null            ┆ ['']          ┆ Never Hike Alone:  │
│ Friday the…         ┆ A Friday th…        ┆                 ┆               ┆ A Friday the…      │
│ When a rare shark   ┆ Elusive ‘Alien Of   ┆ Alexander Smith ┆ ['']          ┆ null               │
│ was caught, …       ┆ The Sea ‘ Ca…       ┆                 ┆               ┆                    │
│ Donald Trump has    ┆ Trump’s Genius Poll ┆ Gloria Christie ┆ ['']          ┆ null               │
│ the unnerving…      ┆ Is Complet…         ┆                 ┆               ┆                    │
└─────────────────────┴─────────────────────┴─────────────────┴───────────────┴────────────────────┘

In [3]:
df_clean = preprocess(df_sample)
df_clean.select(natural_language_cols).head()

shape: (5, 5)
┌───────────────────────┬──────────────────────┬────────────────┬───────────────┬──────────────────┐
│ content               ┆ title                ┆ authors        ┆ meta_keywords ┆ meta_description │
│ ---                   ┆ ---                  ┆ ---            ┆ ---           ┆ ---              │
│ str                   ┆ str                  ┆ str            ┆ str           ┆ str              │
╞═══════════════════════╪══════════════════════╪════════════════╪═══════════════╪══════════════════╡
│ sometim power         ┆ church congreg bring ┆ ruth harri     ┆               ┆ null             │
│ christma make wi…     ┆ gift wait…           ┆                ┆               ┆                  │
│ awaken <num> strand   ┆ awaken <num> strand  ┆ zurich time    ┆               ┆ null             │
│ dna reconn…           ┆ dna reconn…          ┆                ┆               ┆                  │
│ never hike alon       ┆ never hike alon -    ┆ null           ┆               ┆ never hike alon  │
│ friday <num> t…       ┆ friday <num>…        ┆                ┆               ┆ friday <num> t…  │
│ rare shark caught     ┆ elus alien sea       ┆ alexand smith  ┆               ┆ null             │
│ scientist le…         ┆ caught scientis…     ┆                ┆               ┆                  │
│ donald trump unnerv   ┆ trump geniu poll     ┆ gloria christi ┆               ┆ null             │
│ abil abil …           ┆ complet resul…       ┆                ┆               ┆                  │
└───────────────────────┴──────────────────────┴────────────────┴───────────────┴──────────────────┘

In [4]:
raw_file = '../data/raw/995,000_rows.csv'
preprocessed_file = '../data/preprocessed/995,000_rows_preprocessed.csv'
preprocessed_file

'../data/preprocessed/995,000_rows_preprocessed.csv'

In [6]:
preprocess_file(
    filepath=raw_file,
    outpath=preprocessed_file,
    chunk_size=50_000,
)

7/20 chunks processed - 350000 rows so far

ComputeError: could not parse `"COP23, pipeline, Pope Francis, Ryan Zinke, Paris agreement, TransCanada's, antibiotics, denial"` as dtype `f64` at column 'id' (column number 2)

The current offset in the file is 481643 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `"COP23, pipeline, Pope Francis, Ryan Zinke, Paris agreement, TransCanada's, antibiotics, denial"` to the `null_values` list.

Original error: ```invalid primitive value found during CSV parsing```